"""Increase role column length

Revision ID: 057707e33458
Revises: 477dd827cd1f
Create Date: 2025-03-11 10:08:06.151287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057707e33458'
down_revision = '477dd827cd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
