"""Add vehicle_number and booking_id to Booking model

Revision ID: 08bac078d30f
Revises: 2c0d79c9f7aa
Create Date: 2025-03-03 00:21:49.190486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08bac078d30f'
down_revision = '2c0d79c9f7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('vehicle_number', sa.String(length=20), nullable=False, server_default='NA')
        )
        batch_op.add_column(
            sa.Column('booking_id', sa.String(length=50), unique=True, nullable=False, server_default='NA')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('booking_id')
        batch_op.drop_column('vehicle_number')

    # ### end Alembic commands ###
