"""Add booked_by field

Revision ID: 1884ef3afa52
Revises: a445ad534e2b
Create Date: 2025-02-16 00:41:59.242857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1884ef3afa52'
down_revision = 'a445ad534e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booked_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['booked_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('booked_by')

    # ### end Alembic commands ###
