"""Add booked_by and active fields

Revision ID: 1dee8ce40f8a
Revises: 1884ef3afa52
Create Date: 2025-02-16 01:22:36.076605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dee8ce40f8a'
down_revision = '1884ef3afa52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
