"""Added two_wheeler_spaces_booked and four_wheeler_spaces_booked fields to ParkingSpot

Revision ID: 3f4df3eff907
Revises: f32fd81ab2a7
Create Date: 2025-02-18 03:11:45.252480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4df3eff907'
down_revision = 'f32fd81ab2a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_wheeler_spaces_booked', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('four_wheeler_spaces_booked', sa.Integer(), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spots', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('four_wheeler_spaces_booked')
        batch_op.drop_column('two_wheeler_spaces_booked')

    # ### end Alembic commands ###
