"""empty message

Revision ID: 46efa4b1a955
Revises: 3f4df3eff907
Create Date: 2025-02-18 05:39:55.568312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46efa4b1a955'
down_revision = '3f4df3eff907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booked_vehicle_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('booked_vehicle_type')

    # ### end Alembic commands ###
