"""Add vehicle_number and status to Booking

Revision ID: 477dd827cd1f
Revises: 
Create Date: 2025-03-11 06:01:48.075182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477dd827cd1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('vehicle_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'NA'::character varying"))
        batch_op.drop_constraint('booking_booking_id_key', type_='unique')
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.VARCHAR(length=50), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('booking_booking_id_key', ['booking_id'])
        batch_op.alter_column('vehicle_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'NA'::character varying"))

    # ### end Alembic commands ###
