"""Updated ParkingSpot: removed google_maps_link, added lat and lng

Revision ID: 5fb6f06d5a62
Revises: b2bd8dd36afc
Create Date: 2025-02-25 11:52:04.609624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb6f06d5a62'
down_revision = 'b2bd8dd36afc'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('parking_spot', sa.Column('lat', sa.Float(), nullable=False, server_default='12.9716'))
    op.add_column('parking_spot', sa.Column('lng', sa.Float(), nullable=False, server_default='77.5946'))
    op.drop_column('parking_spot', 'google_maps_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_maps_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###
