"""Final authentication setup

Revision ID: 6bb4659e75fe
Revises: 45890c7a6e61
Create Date: 2025-02-10 14:06:51.327617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb4659e75fe'
down_revision = '45890c7a6e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parking_spot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_spot',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('availability', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='parking_spot_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='parking_spot_pkey')
    )
    # ### end Alembic commands ###
