"""Initial migration

Revision ID: 6faea6f4e177
Revises: 
Create Date: 2025-03-12 12:48:45.360290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6faea6f4e177'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('vehicle_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'NA'::character varying"))
        batch_op.drop_constraint('booking_booking_id_key', type_='unique')
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.VARCHAR(length=50), server_default=sa.text("'NA'::character varying"), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('booking_booking_id_key', ['booking_id'])
        batch_op.alter_column('vehicle_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'NA'::character varying"))

    op.drop_table('payment_details')
    # ### end Alembic commands ###
