"""Add phone_number column to Booking

Revision ID: 874217e006c8
Revises: 4002a4366598
Create Date: 2025-03-22 16:27:04.912464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874217e006c8'
down_revision = '4002a4366598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.drop_column('two_wheeler')
        batch_op.drop_column('four_wheeler')

    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.drop_column('four_wheeler_spaces')
        batch_op.drop_column('two_wheeler_spaces')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_wheeler_spaces', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('four_wheeler_spaces', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('four_wheeler', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('two_wheeler', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
