"""Add google_maps_link and vehicle space counts to ParkingSpot

Revision ID: 9a75f45dc9e1
Revises: 08bb096cecea
Create Date: 2025-02-14 20:26:10.236240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a75f45dc9e1'
down_revision = '08bb096cecea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_maps_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('two_wheeler_spaces', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('four_wheeler_spaces', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('parking_spots', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('four_wheeler_spaces')
        batch_op.drop_column('two_wheeler_spaces')
        batch_op.drop_column('google_maps_link')

    # ### end Alembic commands ###
