"""Removed approved column

Revision ID: 9ce430f641d9
Revises: d4784a3eda2f
Create Date: 2025-03-11 11:33:00.783883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce430f641d9'
down_revision = 'd4784a3eda2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
