"""Added status column to ParkingSpot

Revision ID: a445ad534e2b
Revises: 0f8129da7789
Create Date: 2025-02-16 00:30:34.014273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a445ad534e2b'
down_revision = '0f8129da7789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
