"""Add created_at and updated_at to users

Revision ID: a82278e62b00
Revises: c1628470173f
Create Date: 2025-02-15 21:07:27.779499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82278e62b00'
down_revision = 'c1628470173f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_maps_link', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('two_wheeler_spaces', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('four_wheeler_spaces', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('available_from', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('available_to', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('parking_spots', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('available_to')
        batch_op.drop_column('available_from')
        batch_op.drop_column('description')
        batch_op.drop_column('four_wheeler_spaces')
        batch_op.drop_column('two_wheeler_spaces')
        batch_op.drop_column('google_maps_link')

    # ### end Alembic commands ###
