"""Remove character limit for google maps link

Revision ID: c1628470173f
Revises: e3ad370769ea
Create Date: 2025-02-15 11:17:08.460285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1628470173f'
down_revision = 'e3ad370769ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spots', schema=None) as batch_op:
        batch_op.alter_column('google_maps_link',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spots', schema=None) as batch_op:
        batch_op.alter_column('google_maps_link',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
