"""Add is_approved column to booking

Revision ID: cd32820d3a21
Revises: d607668a1500
Create Date: 2025-03-23 02:06:41.720752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd32820d3a21'
down_revision = 'd607668a1500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
