"""Add PaymentDetails table

Revision ID: def7c5e3fed1
Revises: ad38596179d7
Create Date: 2025-03-11 20:46:15.456557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def7c5e3fed1'
down_revision = 'ad38596179d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_details', schema=None) as batch_op:
        batch_op.alter_column('upi_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.drop_constraint('payment_details_upi_id_key', type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('payment_details', schema=None) as batch_op:
        batch_op.create_unique_constraint('payment_details_upi_id_key', ['upi_id'])
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('upi_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
