"""Add available_from and available_to to ParkingSpot

Revision ID: e3ad370769ea
Revises: 9a75f45dc9e1
Create Date: 2025-02-14 20:55:34.140928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ad370769ea'
down_revision = '9a75f45dc9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_from', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('available_to', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spots', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('available_to')
        batch_op.drop_column('available_from')

    # ### end Alembic commands ###
